### ISSUE TITLE
Testing with this package

### ISSUE THREAD

**Issue by IAndreaGiuseppe** [protonemedia/laravel-ffmpeg#227] opened 2020-09-03 22:01 UTC
Hi, I'm using this package and have implements a job that convert videos.

Running the test suite I get:
`FFMpeg\Exception\ExecutableNotFoundException: Unable to load FFMpeg`

mainly because I don't have FFMpeg locally installed.

Could you, please, provide a `FFMpeg::fake()` similar to any other fake on laravel?
Thanks

**Comment by pascalbaljet** [comment] 2020-09-04 09:12
Duplicate of https://github.com/protonemedia/laravel-ffmpeg/issues/163

TLDR: mock the Facade with the `shouldReceive` method: https://laravel.com/docs/master/mocking#mocking-facades

**Closed by pascalbaljet** 2020-09-04 09:12 UTC
