### ISSUE TITLE
convert single mp3 to m3u8

### ISSUE THREAD

**Issue by nemesisKO** [protonemedia/laravel-ffmpeg#359] opened 2021-11-30 14:26 UTC
i searched a lot and didnt find for convert just single mp3 file to m3u8 format. can you help me with it?
thanks

**Comment by pascalbaljet** [comment] 2021-12-19 18:27
Duplicate of https://github.com/protonemedia/laravel-ffmpeg/issues/319

**Closed by pascalbaljet** 2021-12-19 18:27 UTC
